package com.mubin.quant.audit;

public enum AuditEventType {
    ORDER_EVENT_APPLIED,
    DUPLICATE_REPORT,
    ORPHAN_REPORT,
    STATE_CONFLICT,
    RFQ_EXPIRED,
    POSITION_UPDATED,
    RECON_DIFF_DETECTED,
    RECON_STATE_CORRECTED,
    HEDGE_TRIGGERED,
    HEDGE_WAITED,
    HEDGE_ORDER_SUBMITTED
}
